version = 0.1

[default]
[default.global.parameters]
stack_name = "serverless-typescript-api"
region = "ap-southeast-2"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Environment=\"dev\""
s3_prefix = "add-sls-repo"
image_repositories = []
stack_name = "add-sls-repo"

